config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :movements

  root 'welcome#index'

end

app/models/movement.rb
class Movement < Flexirest::Base
  @@token = nil
  base_url       PUBBLICALO['base_url']
  before_request :api_authenticate

  get :all,  "/all"
  get :find, "/accounts"

  def idConto
    case livello
    when 1
      return conto.chomp(".00.00.00.000")
    when 2
      return conto.chomp(".00.00.000")
    when 3
      return conto.chomp(".00.000")
    when 4
      return conto.chomp(".000")
    else
      return conto
    end
  end

  def perc_aa_prec
    if importo_prec.nil?
      return nil
    else
      diff = importo.to_f - importo_prec.to_f
#      return ((importo.to_f * 100) / importo_prec.to_f).round(2)
      return ((diff.to_f * 100) / importo_prec.to_f).round(2)
    end
  end

  def perc_su_tot(cumulato_sup)
    return ((importo.to_f * 100) / cumulato_sup.to_f).round(2)
  end

  private

  def api_authenticate (name, request)
    # rinnova token
    # curl -k -d "grant_type=client_credentials" -H "Authorization: Basic UURrSEhQdnoyOTRGM2U4R3JiT0duNjRGbW1jYTo3YmZ6VkNLY25sVlZOcHJCUVZHQXc0aURvOGth" https://api.integrazione.lispa.it/oauth2/token
    # esegue richiesta
    # curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer efb49d75-fe2d-32e6-9176-951120fd1e53' 'https://api.integrazione.lispa.it/t/servizi.rl/pubblica.lo/1.0/accounts?mandante=130&societa=1000&tipo_conto=E&livello=1&sort_column=conto&sort_order=ASC&page=1&per_page=20'
    return if PUBBLICALO['api_gw'] == "false"
    get_token
    request.headers["Authorization"] = "Bearer "+@@token.token
  end

  def get_token
    site_path      = PUBBLICALO['site_path']
    token_url      = PUBBLICALO['token_url']
    client_id      = PUBBLICALO['client_id']
    client_secret  = PUBBLICALO['client_secret']

    if @@token.nil? || @@token.expired?
      client = OAuth2::Client.new(client_id, client_secret, :site => site_path, :token_url => token_url)
      #code    = client.client_credentials.authorization(client_id, client_secret)
      #@@token = client.get_token(:headers => {'Authorization' => code},
      #                           :content_type => 'application/x-www-form-urlencoded',
      #                           :grant_type => 'client_credentials')
      @@token = client.client_credentials.get_token
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
# protect_from_forgery with: :exception
  protect_from_forgery except: :show
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  def restore_filter
    if params[:tipo_conto].nil? then
      params[:tipo_conto] = "E"
    else
      params[:tipo_conto] = "U"
    end
    if !session[:movements_tipo_conto].nil? and params[:anno].nil? then
      params[:tipo_conto] = session[:movements_tipo_conto]
    end

#      if !session[:movements_tipo_conto].nil? then
#        params[:tipo_conto] = session[:movements_tipo_conto]
#      else
#        params[:tipo_conto] = "U"
#      end

    @last_year = Time.now.year
#    if Movement.find(anno: @last_year, conto: params[:tipo_conto]+".0.00.00.00.000").count == 0 then
#      @last_year = @last_year - 1
#    end

    if params[:anno].nil? then
      if !session[:movements_anno].nil? then
        params[:anno] = session[:movements_anno]
      else
        params[:anno] = @last_year
      end
    end

    if params[:livello].nil? then
      if !session[:movements_livello].nil? then
        params[:livello] = session[:movements_livello]
      else
        params[:livello] = 1
      end
    end

    if params[:ricerca].nil? && !session[:movements_ricerca].nil? then
      params[:ricerca] = session[:movements_ricerca]
    end

    change_order = false
    if params[:sort_column].nil? then
      if !session[:movements_sort_column].nil? then
        params[:sort_column] = session[:movements_sort_column]
      else
        params[:sort_column] = "conto"
      end
    else
      if !session[:movements_sort_column].nil? && session[:movements_sort_column] == params[:sort_column] then
        change_order = true
      end
    end

    if change_order then
      if session[:movements_sort_order] == "ASC" then
        params[:sort_order] = "DESC"
      else
        params[:sort_order] = "ASC"
      end
    end
    if params[:sort_order].nil?
      if !session[:movements_sort_order].nil? then
        params[:sort_order] = session[:movements_sort_order]
      else
        params[:sort_order] = "ASC"
      end
    end

  end

  # GET /movements
  # GET /movements.json
  def index
    restore_filter
    @total = Movement.find(anno: params[:anno], conto: params[:tipo_conto]+".0.00.00.00.000")
    if params[:livello] == '0' then params[:livello] = '' end
    @movements = Movement.find(anno: params[:anno], tipo_conto: params[:tipo_conto], livello: params[:livello],
      ricerca: params[:ricerca], sort_column: params[:sort_column], sort_order: params[:sort_order], per_page: 200)

    session[:movements_anno] = params[:anno]
    session[:movements_tipo_conto] = params[:tipo_conto]
    session[:movements_livello] = params[:livello]
    session[:movements_ricerca] = params[:ricerca]
    session[:movements_sort_column] = params[:sort_column]
    session[:movements_sort_order] = params[:sort_order]

    respond_to do |format|
      format.html
      format.xls
    end

  end

  # GET /movements/1
  # GET /movements/1.json
  def show
    @movements = Movement.find(conto: params[:conto], anno: params[:anno], tipo_conto: params[:tipo_conto], livello: params[:livello],
                                          sort_column: params[:sort_column], sort_order: params[:sort_order])
    @cumulato_sup = params[:importo].to_f
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(anno: params[:anno], tipo_conto: params[:tipo_conto], livello: params[:livello])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movement).permit(:anno, :mese, :tipo_conto, :livello, :conto, :voce, :importo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_barra_istituzionale.html.erb
<a href="#content" class="sr-only sr-only-focusable">Vai al contenuto principale</a>
<div id="barra_istituzionale" class="clearfix">
  <div class="logo hidden-xs">
    <a href="http://www.consiglio.regione.lombardia.it">
      <%= image_tag("consiglio_regionale_lombardia_logo.png", alt: "Consiglio regionale della Lombardia", width: "175", height: "91") %>
    </a>
  </div>

  <div class="numero_verde text-center visible-lg"></div>

  <div class="text-center">
    <div class="area_titolo">
      <div class="sigla" tabindex="0"><%= link_to "Pubblica.Lo", root_path %></div>
      <span class="separatore_titolo"> | </span>
      <div class="titolo_esteso" tabindex="0"> Il bilancio del Consiglio regionale <span class="hidden-xs hidden-sm">della Lombardia</span></div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="text-center">
  <span>Consiglio regionale della Lombardia - Via Fabio Filzi, 22 - 20124 Milano - Tel. 02.67482.1</span>
</div>

app/views/layouts/_pannello_ricerca.html.erb
<a href="#salta_ricerca" class="sr-only sr-only-focusable">Salta pannello ricerca</a>
<div id="barra_ricerca" class="well well-sm well-lispa-dark">
  <%= form_tag movements_path, :method => 'get', :class => 'form-inline', :role => 'form' do %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-7">
          <div class="form-group">
            <%= label_tag 'anno', 'anno', {class: 'sr-only'} %>
            <%= select_tag "anno", options_for_select(((2014..@last_year).to_a.reverse), params[:anno]),
            {class: 'select optional form-control', :onchange => "this.form.submit()"} %>
          </div>
          <div class="form-group">
            <%= label_tag 'tipo_conto', 'tipo conto', {class: 'sr-only'} %>
            <%= check_box_tag "tipo_conto", params[:tipo_conto],
                if params[:tipo_conto]=="U" then true else false end,
                data: {:toggle => "toggle",
                       :on => "Spese",
                       :off => "Entrate",
                       :onstyle => "success",
                       :offstyle => "info"}
            %>
          </div>
          <div class="form-group">
            <%= label_tag 'livello', 'Livello:' %>&nbsp;&nbsp;&nbsp;&nbsp;
            <%= text_field_tag 'livello', params[:livello], type: 'text',
            "data-provide" => 'slider',
            "data-slider-ticks" => '[0, 1, 2, 3, 4, 5]',
            "data-slider-ticks-labels" => '["Tutti","1", "2", "3", "4", "5"]',
            "data-slider-min" => '0',
            "data-slider-max" => '5',
            "data-slider-step" => '1',
            "data-slider-value" => params[:livello],
            "data-slider-tooltip" => 'show',
            onchange: 'this.form.submit()'
            %>
          </div>
        </div>
        <div class="col-sm-5">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1" data-toggle= "tooltip"  data-placement= "top"
                  title="La ricerca è collegata col livello del piano dei conti selezionato.
                         Selezionando 'Tutti' senza una parola di ricerca vengono visualizzati tutti i livelli del
                         piano dei conti valorizzati.
                  ">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </span>
            <%= label_tag 'ricerca', 'ricerca', {class: 'sr-only'} %>
            <%= text_field_tag :ricerca, params[:ricerca], :class => "form-control", :placeholder => "Spese per / Entrate da ...", :type => "search" %>
            <span class="input-group-btn">
              <%= button_tag(:class => "btn btn-default", :type => 'submit', :name => 'search', :value => 'cerca') do  %>
                Cerca
              <% end %>
            </span>
          </div>

          <a class="btn btn-default btn-lg" id="link_arconet" data-toggle="tooltip" data-placement="top"
             title="Piano dei conti integrato degli enti territoriali e dei loro organismi e enti strumentali."
             href="http://www.rgs.mef.gov.it/VERSIONE-I/e_government/amministrazioni_pubbliche/arconet/piano_dei_conti_integrato/"
             aria-label="link al sito Arconet" role="button">
             <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
          </a>
          <%= link_to movements_path(format: "xls"), class: "btn btn-default btn-lg",
              title: "Scarica la tua interrogazione in formato foglio di calcolo.",
              role: "button",
              data: { :toggle => "tooltip", :placement => "top" } do %>
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<span id="salta_ricerca"></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Pubblica Lombardia">
  <title>Pubblica.Lo</title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'lomb_ver' %>
  <%= stylesheet_link_tag 'pubblicalo' %>
  <%= stylesheet_link_tag 'bootstrap-slider' %>
  <%= stylesheet_link_tag 'bootstrap-toggle' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>
</head>
<body>
   <%= render :partial => "layouts/barra_istituzionale" %>
   <%= yield %>
   <%= render :partial => "layouts/footer" %>
   <script>
   $(function () {
     $("input.slider").bootstrapSlider();
     $('#livello').slider({
       formatter: function(value) {
         if (value == 0) {
           testo = "Tutti i livelli";
         } else {
           var testo = "Livello del conto: " + value;
         }
         return testo;
      }
     });
     $('[data-toggle="tooltip"]').tooltip()
     $('#tipo_conto').bootstrapToggle();
   })
   $("#tipo_conto").change(function() {
     if($(this).prop("checked") == true) {
       $(this).val('U');
     } else {
       $(this).val('E');
     }
     this.form.submit();
   });
   $('#livello').slider({
     formatter: function(value) {
       if (value == 0) {
         testo = "Tutti i livelli";
       } else {
         var testo = "Livello del conto: " + value;
       }
       return testo;
    }
   });
   </script>
 </body>
</html>

app/views/movements/_form.html.erb
<%= form_for(@movement) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :anno %><br>
    <%= f.number_field :anno %>
  </div>
  <div class="field">
    <%= f.label :mese %><br>
    <%= f.number_field :mese %>
  </div>
  <div class="field">
    <%= f.label :tipo_conto %><br>
    <%= f.text_field :tipo_conto %>
  </div>
  <div class="field">
    <%= f.label :livello %><br>
    <%= f.number_field :livello %>
  </div>
  <div class="field">
    <%= f.label :conto %><br>
    <%= f.text_field :conto %>
  </div>
  <div class="field">
    <%= f.label :voce %><br>
    <%= f.text_area :voce %>
  </div>
  <div class="field">
    <%= f.label :importo %><br>
    <%= f.text_field :importo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<%= render :partial => "layouts/pannello_ricerca" %>

<div id="content" class="container-fluid">

  <p id="notice"><%= notice %></p>
  <div class="text-center"><span id="voce_<%= params[:tipo_conto] %>">Totale
    <% if params[:tipo_conto] == "U" %>Spese<% else %>Entrate<% end %> cumulate <%= params[:anno] %></span>:
    <strong><span id="cumul_anno_<%= params[:tipo_conto] %>"><%= unless @total[0].nil?; number_to_currency(@total[0].importo, locale: :it); end %></span></strong>
  </div>
  <div class="table-responsive">
  <table class="table table-hover">
    <%= form_tag movements_path, :method => 'get', :class => 'form-group', :role => 'form' do %>
      <thead>
        <tr>
          <th>
            <%= button_tag(:class => "btn btn-sort_column title", :type => 'submit', :name => 'sort_column', :value => 'conto') do  %>
              Conto
              <% if params[:sort_column] == 'conto' %>
                <% if params[:sort_order] == 'DESC' %>
                  <span class="glyphicon glyphicon-sort-by-attributes-alt active"
                        title='ordinamento discendente'></span>
                <% else %>
                  <span class="glyphicon glyphicon-sort-by-attributes active"
                        title='ordinamento ascendente'></span>
                <% end %>
              <% else %>
                <span class="glyphicon glyphicon-sort"
                      title='clicca per ordinare per conto'></span>
              <% end %>
            <% end %>
          </th>
          <th></th>
          <th>Voce</th>
          <th class="text-right">
            <%= button_tag(:class => "btn btn-sort_column title", :type => 'submit', :name => 'sort_column', :value => 'importo') do  %>
              Cumulo <%= params[:anno] %>
              <% if params[:sort_column] == 'importo' %>
                <% if params[:sort_order] == 'DESC' %>
                  <span class="glyphicon glyphicon-sort-by-attributes-alt active"
                        title='ordinamento discendente'></span>
                <% else %>
                  <span class="glyphicon glyphicon-sort-by-attributes active"
                        title='ordinamento ascendente'></span>
                <% end %>
              <% else %>
                <span class="glyphicon glyphicon-sort"
                      title='clicca per ordinare per importo'></span>
              <% end %>
            <% end %>
          </th>
          <th class="text-right">
          % <%= (params[:anno].to_i - 1) %>
          </th>
          <th class="text-right">
            Totale <%= (params[:anno].to_i - 1) %>
          </th>
        </tr>
      </thead>
    <% end %>
      <tbody>
        <% @movements.each_with_index do |movement, index| %>
          <tr>
            <td class="width_10_pc">
              <% if params[:livello].blank? %>
                <% case movement.livello %>
                <% when 0 %>
                  <div><%= movement.conto %></div>
                <% when 1 %>
                  <div><span class="label label-success">1</span>&nbsp;<%= movement.conto %></div>
                <% when 2 %>
                  <div><span class="label blank">&nbsp;</span><span class="label label-success">2</span>&nbsp;<%= movement.conto %></div>
                <% when 3 %>
                  <div><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label label-success">3</span>&nbsp;<%= movement.conto %></div>
                <% when 4 %>
                  <div><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label label-success">4</span>&nbsp;<%= movement.conto %></div>
                <% when 5 %>
                  <div><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label blank">&nbsp;</span><span class="label label-success">5</span>&nbsp;<%= movement.conto %></div>
                <% end %>
              <% else %>
                <%= movement.conto %>
              <% end %>
            </td>
            <td class="width_10_pc">
              <div class="btn-group" role="group" data-turbolinks="false">
              <% if movement.livello < 5 %>
                  <a class="btn btn-primary btn-md" role="button" href="#<%= movement.id %>" aria-expanded="false" aria-label="dettaglio"
                    id="btn_movement" data-toggle="tooltip" data-placement="top"
                    title="Livello inferiore del conto"
                    aria-controls="#<%= movement.id %>" onclick="subAccounts(this, '<%= movement.idConto %>', '<%= movement.importo %>')"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
              <% end %>
              <% if movement.livello < 6 %>
                  <a class="btn btn-primary btn-md" role="button" href="#<%= movement.id %>" aria-expanded="false" aria-label="grafici"
                     id="btn_grafico" data-toggle="tooltip" data-placement="right"
                     title="Grafico a barre mese su mese, a torta con i livelli superiori."
                     aria-controls="#<%= movement.id %>" onclick="grafici(this, '<%= movement.idConto %>')"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span></a>
                </div>
              <% end %>
            </td>
            <td id="voce_<%= movement.idConto %>"><%= movement.voce %></td>
            <td id="cumul_anno_<%= movement.idConto %>" class="text-right text-nowrap width_10_pc""><%= number_to_currency(movement.importo, locale: :it) %></td>
            <td class="text-right text-nowrap width_5_pc"">
              <% @perc = number_to_percentage(movement.perc_aa_prec, precision: 2, locale: :it) %>
              <%= @perc %>
              <span class="<%= @perc.to_f > 0 ? 'glyphicon glyphicon-circle-arrow-up orange' : 'glyphicon glyphicon-circle-arrow-down blue' %>"
                    aria-hidden="true"></span>
            </td>
            <td class="text-right text-nowrap width_10_pc""><%= number_to_currency(movement.importo_prec, locale: :it) %></td>
            <td class="hidden" id="liv_conto_<%= movement.idConto %>"><%= movement.livello %></td>
            <td class="hidden">
              <ul id="data_<%= movement.idConto %>">
                <li><%= movement.importo_01 %></li>
                <li><%= movement.importo_02 %></li>
                <li><%= movement.importo_03 %></li>
                <li><%= movement.importo_04 %></li>
                <li><%= movement.importo_05 %></li>
                <li><%= movement.importo_06 %></li>
                <li><%= movement.importo_07 %></li>
                <li><%= movement.importo_08 %></li>
                <li><%= movement.importo_09 %></li>
                <li><%= movement.importo_10 %></li>
                <li><%= movement.importo_11 %></li>
                <li><%= movement.importo_12 %></li>
              </ul>
            </td>
            <td class="hidden">
              <ul id="preced_<%= movement.idConto %>">
                <li><%= movement.importo_01_prec.nil? ? 0 : movement.importo_01_prec %></li>
                <li><%= movement.importo_02_prec.nil? ? 0 : movement.importo_02_prec %></li>
                <li><%= movement.importo_03_prec.nil? ? 0 : movement.importo_03_prec %></li>
                <li><%= movement.importo_04_prec.nil? ? 0 : movement.importo_04_prec %></li>
                <li><%= movement.importo_05_prec.nil? ? 0 : movement.importo_05_prec %></li>
                <li><%= movement.importo_06_prec.nil? ? 0 : movement.importo_06_prec %></li>
                <li><%= movement.importo_07_prec.nil? ? 0 : movement.importo_07_prec %></li>
                <li><%= movement.importo_08_prec.nil? ? 0 : movement.importo_08_prec %></li>
                <li><%= movement.importo_09_prec.nil? ? 0 : movement.importo_09_prec %></li>
                <li><%= movement.importo_10_prec.nil? ? 0 : movement.importo_10_prec %></li>
                <li><%= movement.importo_11_prec.nil? ? 0 : movement.importo_11_prec %></li>
                <li><%= movement.importo_12_prec.nil? ? 0 : movement.importo_12_prec %></li>
              </ul>
            </td>
          </tr>
          <% if movement.livello < 6 %>
            <tr class="collapse" id="<%= movement.id %>" role="tabpanel">
              <td colspan="7" class="bg_lev_<%= movement.livello + 2 - session[:movements_livello].to_i %>">
                <span class="hidden"><%= movement.livello %></span>
                <div id="<%= movement.idConto %>" class="sub_table_container"></div>
              </td>
            </tr>
          <% end %>
        <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.js.erb
<%= render partial: 'show' %>

app/views/welcome/index.html.erb
<div class="area_utente">
  <div class="container-fluid">
  	<span class="nome_utente">
  		<span class="glyphicon glyphicon-home white" role="presentation"></span>
  		Trasparenza conti del Consiglio regionale della Lombardia
  	</span>
  </div>
</div>

<div class="home">
  <div class="well">
    <p class="h4">Questo sito permette di interrogare tutti i pagamenti e le entrate catalogate secondo il piano dei conti delle pubbliche amministrazioni (nuovo SIOPE).</p>
    <p class="h4">Le informazioni sono estratte direttamente dal sistema contabile dell'amministrazione e vengono pubblicate con una frequenza giornaliera.</p>
    <p class="h4">La rappresentazione ricalca i 5 livelli di gerarchia che compongono il piano dei conti, partendo dal raggruppamento piu' alto (1) fino a quello di maggiore dettaglio (5).</p>
    <p class="h4">La ricerca si basa sul livello dei conti selezionato.</p>
    <br/>
    <p class="center">
    <%= link_to movements_path, :class => "btn btn-primary btn-lg" do %>
       Entra <span class="glyphicon glyphicon-arrow-right"></span>
    <% end %>
    </p>
  </div>
</div>